# Scraping S&P 500 Index Stocks List

In this project, I have implemented the data scraping pipeline using two distinct methodologies to demonstrate technical versatility in data
acquisition:

•Method 1: Utilized pd.read_html() for rapid table detection and conversion.

•Method 2: Create a manual loop to iterate through the th, tr, and td tags.

### Importing Core Libraries

In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

•requests: Responsible for sending HTTP requests to the target URL and retrieving the raw HTML content from the server.

•BeautifulSoup: Used for parsing the raw HTML into a searchable "Soup" object, allowing for easy navigation through tags (like table, th, tr, and td).

•pandas: The primary data manipulation library used to transform the extracted lists into a structured DataFrame for cleaning and exporting.

•warnings: This library is used to manage system notifications. Calling filterwarnings('ignore') will suppress non-critical warning messages, ensuring that the notebook output remains clean and readable.

In [2]:
url = 'https://stockanalysis.com/list/sp-500-stocks/'
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
}

response = requests.get(url, headers=headers)
print(response)

<Response [200]>

•url: Specifies the target webpage containing the S&P 500 stock list.

•headers (User-Agent): This is a critical security bypass step. By providing a User-Agent string, the script identifies itself as a standard web browser (like Chrome) rather than a bot. This prevents the website from blocking the request due to automated scraping policies.

•requests.get(): Executes the actual retrieval of the page's HTML content using the defined URL and headers.

•<Response [200]>: The output confirms a successful connection. In HTTP status codes, 200 means the server processed the request perfectly and is ready to deliver the data.

In [3]:
soup = BeautifulSoup(response.text, 'html')
print(soup)

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<link href="/_app/immutable/assets/0.DOohLh5d.css" rel="stylesheet"/>
<link href="/_app/immutable/assets/___StockTable.C7eSgymT.css" rel="stylesheet"/><!--[--><!--[--><script async="" src="https://securepubads.g.doubleclick.net/tag/js/gpt.js"></script> <script>
			InvestingChannelQueue = window.InvestingChannelQueue || []
		</script> <script async="" src="https://u5.investingchannel.com/static/uat.js"></script><!--]--><!--]--><!--[--><!--[!--><!--]--> <!--[!--><!--]--> <link href="https://stockanalysis.com/list/sp-500-stocks/" rel="canonical"/> <!--[!--><!--]--> <!--[!--><!--]--> <meta content="A List of All Stocks in the S&amp;P 500 Index" property="og:title"/> <!--[!--><!--]--> <meta content="https://stockanalysis.com/list/sp-500-stocks/" property="og:url"/> <meta content="https://stockanalysis.com/img/bear-vs-bull.jpg" property="og:image"/> <meta content="website" property="og:type"/> <meta content="StockAnalysis" property="og:site_name"/> <meta content="summary_large_image" name="twitter:card"/> <meta content="@stock_analysisx" name="twitter:site"/> <meta content="A List of All Stocks in the S&amp;P 500 Index" name="twitter:title"/> <!--[!--><!--]--> <meta content="https://stockanalysis.com/img/bear-vs-bull.jpg" name="twitter:image"/> <!--[--><!-- --><script type="application/ld+json">{"@context":"https://schema.org","@type":"WebPage","name":"A List of All Stocks in the S&P 500 Index","url":"https://stockanalysis.com/list/sp-500-stocks/"}</script><!-- --><!--]--> <!--[!--><!--]--> <!--[!--><!--]--> <!--[--><!-- --><script type="application/ld+json">{"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"Home","item":"https://stockanalysis.com/"},{"@type":"ListItem","position":2,"name":"Stock Lists","item":"https://stockanalysis.com/list/"},{"@type":"ListItem","position":3,"name":"S&P 500 Index Stocks List","item":"https://stockanalysis.com/list/sp-500-stocks/"}]}</script><!-- --><!--]--><!--]--><title>A List of All Stocks in the S&amp;P 500 Index</title>
<link href="https://stockanalysis.com/favicon.png" rel="shortcut icon"/>
<link href="https://stockanalysis.com/favicon-32x32.png" rel="icon" sizes="32x32" type="image/png"/>
<link href="https://stockanalysis.com/favicon-16x16.png" rel="icon" sizes="16x16" type="image/png"/>
<link href="https://stockanalysis.com/apple-touch-icon.png" rel="apple-touch-icon" sizes="180x180"/>
<meta content="app-id=6751272467" name="apple-itunes-app"/>
<script data-api="/e/api/event" data-domain="stockanalysis.com" defer="" src="/e/js/script.js"></script>
<!-- Google Tag Manager -->
<script>
			;(function (w, d, s, l, i) {
				w[l] = w[l] || []
				w[l].push({ 'gtm.start': new Date().getTime(), event: 'gtm.js' })
				var f = d.getElementsByTagName(s)[0],
					j = d.createElement(s),
					dl = l != 'dataLayer' ? '&l=' + l : ''
				j.async = true
				j.src = 'https://www.googletagmanager.com/gtm.js?id=' + i + dl
				f.parentNode.insertBefore(j, f)
			})(window, document, 'script', 'dataLayer', 'GTM-TPBBBKLR')
		</script>
<!-- End Google Tag Manager -->
</head>
<body data-sveltekit-preload-data="hover">
<!-- Google Tag Manager (noscript) -->
<noscript><iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-TPBBBKLR" style="display: none; visibility: hidden" width="0"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->

•response.text: This is the raw HTML code of the webpage, which currently looks like a massive, unstructured string of characters.

•BeautifulSoup(..., 'html'): This function takes that raw string and "parses" it using an HTML engine. It organizes the code into a hierarchy, much like a family tree (the Document Object Model), where every button, table, and link is a specific "branch".

In [4]:
table = soup.find_all('table')
print(table)

[<table class="symbol-table svelte-1ro3niy" id="main-table"><thead><tr class="svelte-1ro3niy"><!--[--><th class="no-pointer svelte-1ro3niy" draggable="true" id="no"><!--[!-->No.<!--]--></th><th class="sym svelte-1ro3niy" draggable="true" id="s"><!--[!-->Symbol<!--]--></th><th class="slw svelte-1ro3niy" draggable="true" id="n"><!--[!-->Company Name<!--]--></th><th class="svelte-1ro3niy" draggable="true" id="marketCap"><!--[--><!--[--><span class="svelte-1ro3niy">Market Cap <!--[--><!-- --><svg class="w-4 h-4" fill="currentColor" style="max-width:40px" viewbox="0 0 20 20"><path clip-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" fill-rule="evenodd"></path></svg><!-- --><!--]--><!-- --></span><!--]--><!--]--></th><th class="svelte-1ro3niy" draggable="true" id="price"><!--[!-->Stock Price<!--]--></th><th class="svelte-1ro3niy" draggable="true" id="change"><!--[!-->% Change<!--]--></th><th class="tr svelte-1ro3niy" draggable="true" id="revenue"><!--[!-->Revenue<!--]--></th><!--]--></tr></thead><tbody><!--[--><tr class="svelte-1ro3niy"><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">1</td><!--]--><!--]--><!--]--><!--]--><!--[--><td class="sym svelte-1ro3niy"><!-- --><a href="/stocks/nvda/">NVDA</a><!-- --></td><!--]--><!--[!--><!--[!--><!--[!--><!--[--><td class="slw svelte-1ro3niy">NVIDIA Corporation</td><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">4.38T</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">180.25</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[--><!--[--><td class="rr svelte-1ro3niy">-1.58%</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[--><td class="tr svelte-1ro3niy">215.94B</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--></tr><tr class="svelte-1ro3niy"><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">2</td><!--]--><!--]--><!--]--><!--]--><!--[--><td class="sym svelte-1ro3niy"><!-- --><a href="/stocks/aapl/">AAPL</a><!-- --></td><!--]--><!--[!--><!--[!--><!--[!--><!--[--><td class="slw svelte-1ro3niy">Apple Inc.</td><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">3.67T</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">250.12</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[--><!--[--><td class="rr svelte-1ro3niy">-2.21%</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[--><td class="tr svelte-1ro3niy">435.62B</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--></tr><tr class="svelte-1ro3niy"><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">3</td><!--]--><!--]--><!--]--><!--]--><!--[--><td class="sym svelte-1ro3niy"><!-- --><a href="/stocks/googl/">GOOGL</a><!-- --></td><!--]--><!--[!--><!--[!--><!--[!--><!--[--><td class="slw svelte-1ro3niy">Alphabet Inc.</td><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">3.66T</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">302.28</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[--><!--[--><td class="rr svelte-1ro3niy">-0.42%</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[--><td class="tr svelte-1ro3niy">402.84B</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--></tr><tr class="svelte-1ro3niy"><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">4</td><!--]--><!--]--><!--]--><!--]--><!--[--><td class="sym svelte-1ro3niy"><!-- --><a href="/stocks/goog/">GOOG</a><!-- --></td><!--]--><!--[!--><!--[!--><!--[!--><!--[--><td class="slw svelte-1ro3niy">Alphabet Inc.</td><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">3.65T</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">301.46</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[--><!--[--><td class="rr svelte-1ro3niy">-0.58%</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[--><td class="tr svelte-1ro3niy">402.84B</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--></tr><tr class="svelte-1ro3niy"><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">5</td><!--]--><!--]--><!--]--><!--]--><!--[--><td class="sym svelte-1ro3niy"><!-- --><a href="/stocks/msft/">MSFT</a><!-- --></td><!--]--><!--[!--><!--[!--><!--[!--><!--[--><td class="slw svelte-1ro3niy">Microsoft Corporation</td><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">2.94T</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">395.55</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[--><!--[--><td class="rr svelte-1ro3niy">-1.57%</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[--><td class="tr svelte-1ro3niy">305.45B</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--></tr><tr class="svelte-1ro3niy"><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">6</td><!--]--><!--]--><!--]--><!--]--><!--[--><td class="sym svelte-1ro3niy"><!-- --><a href="/stocks/amzn/">AMZN</a><!-- --></td><!--]--><!--[!--><!--[!--><!--[!--><!--[--><td class="slw svelte-1ro3niy">Amazon.com, Inc.</td><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">2.23T</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">207.67</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[--><!--[--><td class="rr svelte-1ro3niy">-0.89%</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[--><td class="tr svelte-1ro3niy">716.92B</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--></tr><tr class="svelte-1ro3niy"><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">7</td><!--]--><!--]--><!--]--><!--]--><!--[--><td class="sym svelte-1ro3niy"><!-- --><a href="/stocks/meta/">META</a><!-- --></td><!--]--><!--[!--><!--[!--><!--[!--><!--[--><td class="slw svelte-1ro3niy">Meta Platforms, Inc.</td><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">1.55T</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">613.71</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[--><!--[--><td class="rr svelte-1ro3niy">-3.83%</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[--><td class="tr svelte-1ro3niy">200.97B</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--></tr><tr class="svelte-1ro3niy"><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">8</td><!--]--><!--]--><!--]--><!--]--><!--[--><td class="sym svelte-1ro3niy"><!-- --><a href="/stocks/avgo/">AVGO</a><!-- --></td><!--]--><!--[!--><!--[!--><!--[!--><!--[--><td class="slw svelte-1ro3niy">Broadcom Inc.</td><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">1.53T</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">322.16</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[--><!--[--><td class="rr svelte-1ro3niy">-4.11%</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[--><td class="tr svelte-1ro3niy">68.28B</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--></tr><tr class="svelte-1ro3niy"><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">9</td><!--]--><!--]--><!--]--><!--]--><!--[--><td class="sym svelte-1ro3niy"><!-- --><a href="/stocks/tsla/">TSLA</a><!-- --></td><!--]--><!--[!--><!--[!--><!--[!--><!--[--><td class="slw svelte-1ro3niy">Tesla, Inc.</td><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">1.47T</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">391.20</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[--><!--[--><td class="rr svelte-1ro3niy">-0.96%</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[--><td class="tr svelte-1ro3niy">94.83B</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--></tr><tr class="svelte-1ro3niy"><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">10</td><!--]--><!--]--><!--]--><!--]--><!--[--><td class="sym svelte-1ro3niy"><!-- --><a href="/stocks/brk.b/">BRK.B</a><!-- --></td><!--]--><!--[!--><!--[!--><!--[!--><!--[--><td class="slw svelte-1ro3niy">Berkshire Hathaway Inc.</td><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">1.06T</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">490.03</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[--><!--[--><td class="rr svelte-1ro3niy">-0.38%</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[--><td class="tr svelte-1ro3niy">371.44B</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--></tr><tr class="svelte-1ro3niy"><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">11</td><!--]--><!--]--><!--]--><!--]--><!--[--><td class="sym svelte-1ro3niy"><!-- --><a href="/stocks/wmt/">WMT</a><!-- --></td><!--]--><!--[!--><!--[!--><!--[!--><!--[--><td class="slw svelte-1ro3niy">Walmart Inc.</td><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">1.01T</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">126.52</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[--><!--[!--><!--[--><td class="rg svelte-1ro3niy">0.95%</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[--><td class="tr svelte-1ro3niy">713.16B</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--></tr><tr class="svelte-1ro3niy"><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">12</td><!--]--><!--]--><!--]--><!--]--><!--[--><td class="sym svelte-1ro3niy"><!-- --><a href="/stocks/lly/">LLY</a><!-- --></td><!--]--><!--[!--><!--[!--><!--[!--><!--[--><td class="slw svelte-1ro3niy">Eli Lilly and Company</td><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">880.03B</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">985.08</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[--><!--[!--><!--[--><td class="rg svelte-1ro3niy">0.80%</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[--><td class="tr svelte-1ro3niy">65.18B</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--></tr><tr class="svelte-1ro3niy"><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">13</td><!--]--><!--]--><!--]--><!--]--><!--[--><td class="sym svelte-1ro3niy"><!-- --><a href="/stocks/jpm/">JPM</a><!-- --></td><!--]--><!--[!--><!--[!--><!--[!--><!--[--><td class="slw svelte-1ro3niy">JPMorgan Chase &amp; Co.</td><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">764.45B</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">283.44</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[--><!--[!--><!--[--><td class="rg svelte-1ro3niy">0.19%</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[--><td class="tr svelte-1ro3niy">168.24B</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--></tr><tr class="svelte-1ro3niy"><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">14</td><!--]--><!--]--><!--]--><!--]--><!--[--><td class="sym svelte-1ro3niy"><!-- --><a href="/stocks/xom/">XOM</a><!-- --></td><!--]--><!--[!--><!--[!--><!--[!--><!--[--><td class="slw svelte-1ro3niy">Exxon Mobil Corporation</td><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">650.52B</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">156.12</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[--><!--[!--><!--[--><td class="rg svelte-1ro3niy">1.69%</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[--><td class="tr svelte-1ro3niy">323.91B</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--></tr><tr class="svelte-1ro3niy"><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">15</td><!--]--><!--]--><!--]--><!--]--><!--[--><td class="sym svelte-1ro3niy"><!-- --><a href="/stocks/v/">V</a><!-- --></td><!--]--><!--[!--><!--[!--><!--[!--><!--[--><td class="slw svelte-1ro3niy">Visa Inc.</td><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">585.41B</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">307.14</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[--><!--[!--><!--[--><td class="rg svelte-1ro3niy">0.21%</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[--><td class="tr svelte-1ro3niy">41.39B</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--></tr><tr class="svelte-1ro3niy"><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">16</td><!--]--><!--]--><!--]--><!--]--><!--[--><td class="sym svelte-1ro3niy"><!-- --><a href="/stocks/jnj/">JNJ</a><!-- --></td><!--]--><!--[!--><!--[!--><!--[!--><!--[--><td class="slw svelte-1ro3niy">Johnson &amp; Johnson</td><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">582.04B</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">241.52</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[--><!--[--><td class="rr svelte-1ro3niy">-0.21%</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[--><td class="tr svelte-1ro3niy">94.19B</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--></tr><tr class="svelte-1ro3niy"><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">17</td><!--]--><!--]--><!--]--><!--]--><!--[--><td class="sym svelte-1ro3niy"><!-- --><a href="/stocks/mu/">MU</a><!-- --></td><!--]--><!--[!--><!--[!--><!--[!--><!--[--><td class="slw svelte-1ro3niy">Micron Technology, Inc.</td><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">478.32B</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">426.13</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[--><!--[!--><!--[--><td class="rg svelte-1ro3niy">5.13%</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[--><td class="tr svelte-1ro3niy">42.31B</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--></tr><tr class="svelte-1ro3niy"><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">18</td><!--]--><!--]--><!--]--><!--]--><!--[--><td class="sym svelte-1ro3niy"><!-- --><a href="/stocks/cost/">COST</a><!-- --></td><!--]--><!--[!--><!--[!--><!--[!--><!--[--><td class="slw svelte-1ro3niy">Costco Wholesale Corporation</td><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">447.39B</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">1,008.43</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[--><!--[!--><!--[--><td class="rg svelte-1ro3niy">0.51%</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[--><td class="tr svelte-1ro3niy">286.27B</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--></tr><tr class="svelte-1ro3niy"><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">19</td><!--]--><!--]--><!--]--><!--]--><!--[--><td class="sym svelte-1ro3niy"><!-- --><a href="/stocks/orcl/">ORCL</a><!-- --></td><!--]--><!--[!--><!--[!--><!--[!--><!--[--><td class="slw svelte-1ro3niy">Oracle Corporation</td><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">446.10B</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">155.11</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[--><!--[--><td class="rr svelte-1ro3niy">-2.54%</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[--><td class="tr svelte-1ro3niy">64.08B</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--></tr><tr class="svelte-1ro3niy"><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">20</td><!--]--><!--]--><!--]--><!--]--><!--[--><td class="sym svelte-1ro3niy"><!-- --><a href="/stocks/ma/">MA</a><!-- --></td><!--]--><!--[!--><!--[!--><!--[!--><!--[--><td class="slw svelte-1ro3niy">Mastercard Incorporated</td><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">444.11B</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">497.99</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[--><!--[!--><!--[--><td class="rg svelte-1ro3niy">0.14%</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]

•soup.find_all('table'): This function searches through the entire organized "Soup" object for every occurrence of the table tag. In web development, tables are the standard container used to store structured lists, such as the S&P 500 stock index.

•table (The variable): The result is a Python List containing the HTML code for every table found on the page. By isolating these tags, we can ignore thousands of lines of irrelevant code

### Method 1: pd.read_html()

In [5]:
df = pd.read_html(str(table))[0]

•str(table): Converts the BeautifulSoup object (which is a Python-specific object) back into a raw HTML string. This is necessary because the Pandas function requires a string or file-like object to process the data.

•pd.read_html(): This is a high-level Pandas function that acts as an "automated table detector". It scans the HTML string specifically for table, tr, and td tags, and automatically transforms them into a structured format.

In [6]:
df

,No.,Symbol,Company Name,Market Cap,Stock Price,% Change,Revenue
0,1,NVDA,NVIDIA Corporation,4.38T,180.25,-1.58%,215.94B
1,2,AAPL,Apple Inc.,3.67T,250.12,-2.21%,435.62B
2,3,GOOGL,Alphabet Inc.,3.66T,302.28,-0.42%,402.84B
3,4,GOOG,Alphabet Inc.,3.65T,301.46,-0.58%,402.84B
4,5,MSFT,Microsoft Corporation,2.94T,395.55,-1.57%,305.45B
...,...,...,...,...,...,...,...
498,499,PAYC,"Paycom Software, Inc.",6.82B,125.71,-0.72%,2.05B
499,500,CPB,The Campbell's Company,6.47B,21.71,0.28%,10.04B
500,501,LW,"Lamb Weston Holdings, Inc.",5.63B,40.55,0.25%,6.47B
501,502,PCG,PG&E Corporation,4.80B,18.14,0.39%,24.94B
502,503,NWS,News Corporation,3.79B,26.76,0.38%,8.62B

### Method 2: Manual Loop

In [15]:
columns = [title.text.strip() for title in soup.find_all('th')]
print(columns)

['No.', 'Symbol', 'Company Name', 'Market Cap', 'Stock Price', '% Change', 'Revenue']

•soup.find_all('th'): The script targets all <th> (Table Header) tags within the parsed HTML. In professional web design, these tags are the designated containers for header text.

•List Comprehension: This concise Pythonic method iterates through the found header tags to build a list of titles in a single, efficient line of code.

•.text.strip(): This is a crucial Data Cleansing step. The .text attribute extracts the raw content, while .strip() removes invisible characters like newlines (\n) or extra spaces that often persist in raw web data.

In [9]:
column_data = soup.find_all('tr')
print(column_data)

[<tr class="svelte-1ro3niy"><!--[--><th class="no-pointer svelte-1ro3niy" draggable="true" id="no"><!--[!-->No.<!--]--></th><th class="sym svelte-1ro3niy" draggable="true" id="s"><!--[!-->Symbol<!--]--></th><th class="slw svelte-1ro3niy" draggable="true" id="n"><!--[!-->Company Name<!--]--></th><th class="svelte-1ro3niy" draggable="true" id="marketCap"><!--[--><!--[--><span class="svelte-1ro3niy">Market Cap <!--[--><!-- --><svg class="w-4 h-4" fill="currentColor" style="max-width:40px" viewbox="0 0 20 20"><path clip-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" fill-rule="evenodd"></path></svg><!-- --><!--]--><!-- --></span><!--]--><!--]--></th><th class="svelte-1ro3niy" draggable="true" id="price"><!--[!-->Stock Price<!--]--></th><th class="svelte-1ro3niy" draggable="true" id="change"><!--[!-->% Change<!--]--></th><th class="tr svelte-1ro3niy" draggable="true" id="revenue"><!--[!-->Revenue<!--]--></th><!--]--></tr>, <tr class="svelte-1ro3niy"><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">1</td><!--]--><!--]--><!--]--><!--]--><!--[--><td class="sym svelte-1ro3niy"><!-- --><a href="/stocks/nvda/">NVDA</a><!-- --></td><!--]--><!--[!--><!--[!--><!--[!--><!--[--><td class="slw svelte-1ro3niy">NVIDIA Corporation</td><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">4.38T</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">180.25</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[--><!--[--><td class="rr svelte-1ro3niy">-1.58%</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[--><td class="tr svelte-1ro3niy">215.94B</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--></tr>, <tr class="svelte-1ro3niy"><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">2</td><!--]--><!--]--><!--]--><!--]--><!--[--><td class="sym svelte-1ro3niy"><!-- --><a href="/stocks/aapl/">AAPL</a><!-- --></td><!--]--><!--[!--><!--[!--><!--[!--><!--[--><td class="slw svelte-1ro3niy">Apple Inc.</td><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">3.67T</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">250.12</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[--><!--[--><td class="rr svelte-1ro3niy">-2.21%</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[--><td class="tr svelte-1ro3niy">435.62B</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--></tr>, <tr class="svelte-1ro3niy"><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">3</td><!--]--><!--]--><!--]--><!--]--><!--[--><td class="sym svelte-1ro3niy"><!-- --><a href="/stocks/googl/">GOOGL</a><!-- --></td><!--]--><!--[!--><!--[!--><!--[!--><!--[--><td class="slw svelte-1ro3niy">Alphabet Inc.</td><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">3.66T</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">302.28</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[--><!--[--><td class="rr svelte-1ro3niy">-0.42%</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[--><td class="tr svelte-1ro3niy">402.84B</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--></tr>, <tr class="svelte-1ro3niy"><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">4</td><!--]--><!--]--><!--]--><!--]--><!--[--><td class="sym svelte-1ro3niy"><!-- --><a href="/stocks/goog/">GOOG</a><!-- --></td><!--]--><!--[!--><!--[!--><!--[!--><!--[--><td class="slw svelte-1ro3niy">Alphabet Inc.</td><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">3.65T</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">301.46</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[--><!--[--><td class="rr svelte-1ro3niy">-0.58%</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[--><td class="tr svelte-1ro3niy">402.84B</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--></tr>, <tr class="svelte-1ro3niy"><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">5</td><!--]--><!--]--><!--]--><!--]--><!--[--><td class="sym svelte-1ro3niy"><!-- --><a href="/stocks/msft/">MSFT</a><!-- --></td><!--]--><!--[!--><!--[!--><!--[!--><!--[--><td class="slw svelte-1ro3niy">Microsoft Corporation</td><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">2.94T</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">395.55</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[--><!--[--><td class="rr svelte-1ro3niy">-1.57%</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[--><td class="tr svelte-1ro3niy">305.45B</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--></tr>, <tr class="svelte-1ro3niy"><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">6</td><!--]--><!--]--><!--]--><!--]--><!--[--><td class="sym svelte-1ro3niy"><!-- --><a href="/stocks/amzn/">AMZN</a><!-- --></td><!--]--><!--[!--><!--[!--><!--[!--><!--[--><td class="slw svelte-1ro3niy">Amazon.com, Inc.</td><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">2.23T</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">207.67</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[--><!--[--><td class="rr svelte-1ro3niy">-0.89%</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[--><td class="tr svelte-1ro3niy">716.92B</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--></tr>, <tr class="svelte-1ro3niy"><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">7</td><!--]--><!--]--><!--]--><!--]--><!--[--><td class="sym svelte-1ro3niy"><!-- --><a href="/stocks/meta/">META</a><!-- --></td><!--]--><!--[!--><!--[!--><!--[!--><!--[--><td class="slw svelte-1ro3niy">Meta Platforms, Inc.</td><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">1.55T</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">613.71</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[--><!--[--><td class="rr svelte-1ro3niy">-3.83%</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[--><td class="tr svelte-1ro3niy">200.97B</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--></tr>, <tr class="svelte-1ro3niy"><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">8</td><!--]--><!--]--><!--]--><!--]--><!--[--><td class="sym svelte-1ro3niy"><!-- --><a href="/stocks/avgo/">AVGO</a><!-- --></td><!--]--><!--[!--><!--[!--><!--[!--><!--[--><td class="slw svelte-1ro3niy">Broadcom Inc.</td><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">1.53T</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">322.16</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[--><!--[--><td class="rr svelte-1ro3niy">-4.11%</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[--><td class="tr svelte-1ro3niy">68.28B</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--></tr>, <tr class="svelte-1ro3niy"><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">9</td><!--]--><!--]--><!--]--><!--]--><!--[--><td class="sym svelte-1ro3niy"><!-- --><a href="/stocks/tsla/">TSLA</a><!-- --></td><!--]--><!--[!--><!--[!--><!--[!--><!--[--><td class="slw svelte-1ro3niy">Tesla, Inc.</td><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">1.47T</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">391.20</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[--><!--[--><td class="rr svelte-1ro3niy">-0.96%</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[--><td class="tr svelte-1ro3niy">94.83B</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--></tr>, <tr class="svelte-1ro3niy"><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">10</td><!--]--><!--]--><!--]--><!--]--><!--[--><td class="sym svelte-1ro3niy"><!-- --><a href="/stocks/brk.b/">BRK.B</a><!-- --></td><!--]--><!--[!--><!--[!--><!--[!--><!--[--><td class="slw svelte-1ro3niy">Berkshire Hathaway Inc.</td><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">1.06T</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">490.03</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[--><!--[--><td class="rr svelte-1ro3niy">-0.38%</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[--><td class="tr svelte-1ro3niy">371.44B</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--></tr>, <tr class="svelte-1ro3niy"><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">11</td><!--]--><!--]--><!--]--><!--]--><!--[--><td class="sym svelte-1ro3niy"><!-- --><a href="/stocks/wmt/">WMT</a><!-- --></td><!--]--><!--[!--><!--[!--><!--[!--><!--[--><td class="slw svelte-1ro3niy">Walmart Inc.</td><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">1.01T</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">126.52</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[--><!--[!--><!--[--><td class="rg svelte-1ro3niy">0.95%</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[--><td class="tr svelte-1ro3niy">713.16B</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--></tr>, <tr class="svelte-1ro3niy"><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">12</td><!--]--><!--]--><!--]--><!--]--><!--[--><td class="sym svelte-1ro3niy"><!-- --><a href="/stocks/lly/">LLY</a><!-- --></td><!--]--><!--[!--><!--[!--><!--[!--><!--[--><td class="slw svelte-1ro3niy">Eli Lilly and Company</td><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">880.03B</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">985.08</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[--><!--[!--><!--[--><td class="rg svelte-1ro3niy">0.80%</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[--><td class="tr svelte-1ro3niy">65.18B</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--></tr>, <tr class="svelte-1ro3niy"><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">13</td><!--]--><!--]--><!--]--><!--]--><!--[--><td class="sym svelte-1ro3niy"><!-- --><a href="/stocks/jpm/">JPM</a><!-- --></td><!--]--><!--[!--><!--[!--><!--[!--><!--[--><td class="slw svelte-1ro3niy">JPMorgan Chase &amp; Co.</td><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">764.45B</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">283.44</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[--><!--[!--><!--[--><td class="rg svelte-1ro3niy">0.19%</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[--><td class="tr svelte-1ro3niy">168.24B</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--></tr>, <tr class="svelte-1ro3niy"><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">14</td><!--]--><!--]--><!--]--><!--]--><!--[--><td class="sym svelte-1ro3niy"><!-- --><a href="/stocks/xom/">XOM</a><!-- --></td><!--]--><!--[!--><!--[!--><!--[!--><!--[--><td class="slw svelte-1ro3niy">Exxon Mobil Corporation</td><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">650.52B</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">156.12</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[--><!--[!--><!--[--><td class="rg svelte-1ro3niy">1.69%</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[--><td class="tr svelte-1ro3niy">323.91B</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--></tr>, <tr class="svelte-1ro3niy"><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">15</td><!--]--><!--]--><!--]--><!--]--><!--[--><td class="sym svelte-1ro3niy"><!-- --><a href="/stocks/v/">V</a><!-- --></td><!--]--><!--[!--><!--[!--><!--[!--><!--[--><td class="slw svelte-1ro3niy">Visa Inc.</td><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">585.41B</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">307.14</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[--><!--[!--><!--[--><td class="rg svelte-1ro3niy">0.21%</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[--><td class="tr svelte-1ro3niy">41.39B</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--></tr>, <tr class="svelte-1ro3niy"><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">16</td><!--]--><!--]--><!--]--><!--]--><!--[--><td class="sym svelte-1ro3niy"><!-- --><a href="/stocks/jnj/">JNJ</a><!-- --></td><!--]--><!--[!--><!--[!--><!--[!--><!--[--><td class="slw svelte-1ro3niy">Johnson &amp; Johnson</td><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">582.04B</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">241.52</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[--><!--[--><td class="rr svelte-1ro3niy">-0.21%</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[--><td class="tr svelte-1ro3niy">94.19B</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--></tr>, <tr class="svelte-1ro3niy"><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">17</td><!--]--><!--]--><!--]--><!--]--><!--[--><td class="sym svelte-1ro3niy"><!-- --><a href="/stocks/mu/">MU</a><!-- --></td><!--]--><!--[!--><!--[!--><!--[!--><!--[--><td class="slw svelte-1ro3niy">Micron Technology, Inc.</td><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">478.32B</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">426.13</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[--><!--[!--><!--[--><td class="rg svelte-1ro3niy">5.13%</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[--><td class="tr svelte-1ro3niy">42.31B</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--></tr>, <tr class="svelte-1ro3niy"><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">18</td><!--]--><!--]--><!--]--><!--]--><!--[--><td class="sym svelte-1ro3niy"><!-- --><a href="/stocks/cost/">COST</a><!-- --></td><!--]--><!--[!--><!--[!--><!--[!--><!--[--><td class="slw svelte-1ro3niy">Costco Wholesale Corporation</td><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">447.39B</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">1,008.43</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[--><!--[!--><!--[--><td class="rg svelte-1ro3niy">0.51%</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[--><td class="tr svelte-1ro3niy">286.27B</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--></tr>, <tr class="svelte-1ro3niy"><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">19</td><!--]--><!--]--><!--]--><!--]--><!--[--><td class="sym svelte-1ro3niy"><!-- --><a href="/stocks/orcl/">ORCL</a><!-- --></td><!--]--><!--[!--><!--[!--><!--[!--><!--[--><td class="slw svelte-1ro3niy">Oracle Corporation</td><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">446.10B</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">155.11</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[--><!--[--><td class="rr svelte-1ro3niy">-2.54%</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[--><td class="tr svelte-1ro3niy">64.08B</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--></tr>, <tr class="svelte-1ro3niy"><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">20</td><!--]--><!--]--><!--]--><!--]--><!--[--><td class="sym svelte-1ro3niy"><!-- --><a href="/stocks/ma/">MA</a><!-- --></td><!--]--><!--[!--><!--[!--><!--[!--><!--[--><td class="slw svelte-1ro3niy">Mastercard Incorporated</td><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">444.11B</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!--[!--><!--[!--><td class="svelte-1ro3niy">497.99</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[--><!--[!--><!--[--><td class="rg svelte-1ro3niy">0.14%</td><!--]--><!--]--><!--]--><!--]--><!--]--><!--]--><!--[!--><!--[!--><!--[--><!--[!--><!--[!--><!

•soup.find_all('tr'): The script searches the "Soup" object for all <tr> (Table Row) tags. In an HTML table, each <tr> represents one complete horizontal record—in this case, one company's worth of data.

•column_data: This variable now stores a list of these row elements. By capturing all rows first, we prepare the script to iterate through them one by one in the upcoming data-cleaning loop.

In [10]:
all_rows = [] 

for row in column_data[1:]:
    row_data = row.find_all('td')
    individual_row = [data.text.strip() for data in row_data]
    
    all_rows.append(individual_row)

•for row in column_data[1:]: We initiate a loop starting from the second element (index 1). Slicing the list this way is essential to skip the header row (th).

•row.find_all('td'): Within each specific row, the script locates all <td> (Table Data) tags, which contain the actual stock values like price and market cap.

•List Comprehension with .strip(): For every row, we create a sub-list by extracting the .text from each cell and immediately applying .strip() to ensure no dirty HTML characters or extra spaces enter our dataset.

•all_rows.append(): Each completed sub-list (representing one company) is added to the all_rows master list, creating a 2D array structure ready for conversion.

In [13]:
df = pd.DataFrame(all_rows, columns=columns)

•pd.DataFrame(): This is the core constructor used to build a labeled, two-dimensional data structure.

•all_rows: This serves as the "Body" of the dataset, containing the 500+ individual stock records extracted during the manual loop.

•columns=columns: This assigns the schema we extracted in colums variable, ensuring every column—from 'No.' to 'Revenue'—is accurately labeled.

In [14]:
df

,No.,Symbol,Company Name,Market Cap,Stock Price,% Change,Revenue
0,1,NVDA,NVIDIA Corporation,4.38T,180.25,-1.58%,215.94B
1,2,AAPL,Apple Inc.,3.67T,250.12,-2.21%,435.62B
2,3,GOOGL,Alphabet Inc.,3.66T,302.28,-0.42%,402.84B
3,4,GOOG,Alphabet Inc.,3.65T,301.46,-0.58%,402.84B
4,5,MSFT,Microsoft Corporation,2.94T,395.55,-1.57%,305.45B
...,...,...,...,...,...,...,...
498,499,PAYC,"Paycom Software, Inc.",6.82B,125.71,-0.72%,2.05B
499,500,CPB,The Campbell's Company,6.47B,21.71,0.28%,10.04B
500,501,LW,"Lamb Weston Holdings, Inc.",5.63B,40.55,0.25%,6.47B
501,502,PCG,PG&E Corporation,4.80B,18.14,0.39%,24.94B
502,503,NWS,News Corporation,3.79B,26.76,0.38%,8.62B